# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://jhipster.github.io/profiles/
# More information on configuration properties: https://jhipster.github.io/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
eureka:
    instance:
        prefer-ip-address: true
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@172.18.169.99:32004/eureka/

spring:
    redis:
        host: 172.18.169.99
        port: 31003
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
   datasource:
    url: jdbc:oracle:thin:@58.246.42.86:1521:orcl
    username: EPC
    password: 1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
    mail:
        host: localhost
        port: 25
        username:
        password:
    thymeleaf:
        cache: true
    zipkin:
        base-url: http://172.18.169.99:32007
        enabled: true
        locator:
            discovery:
                enabled: true
    jmx:
        enabled: false
    http:
      multipart:
        max-file-size: 1000Mb
        max-request-size: 1000Mb

liquibase:
    contexts: prod
    enabled: false

service:
    loginUrl: http://172.18.169.99:31002/appframe-web/u/submitLogin.do
    menuUrl: http://172.18.169.99:31002/appframe-web/platform/appframe/afauser/getMenuRelation.do

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias yxxt -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        keyStoreType: PKCS12
#        keyAlias: yxxt
# ===================================================================
server:
    port: 8281
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024
# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://jhipster.github.io/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Cache configuration
        hazelcast: # Hazelcast distributed cache
            time-to-live-seconds: 3600
            backup-count: 1
    cors:
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        allowed-headers: "*"
        exposed-headers:
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: dd193106606a1136102a3683cbf17aba3c779545
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: fair-cloud-server@localhost
        base-url: http://my-server-url-to-change # Modify according to your server's URL
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: fair-cloud-server
        prometheus:
            enabled: false
            endpoint: /prometheusMetrics
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512
        spectator-metrics: # Reports Spectator Circuit Breaker metrics in the logs
            enabled: false
            # edit spring.metrics.export.delay-millis to set report frequency

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://jhipster.github.io/common-application-properties/
# ===================================================================

application:


finance:
    apigateway:
        authUrl: http://10.168.6.124:8080/api/authenticate
        authUserName: admin
        authPasswd: admin
    permCheckEnabled: true
    singleUserLogin: false

jasypt:
    encryptor:
        password: hztech2018

pagehelper:
    autoDialect: true
    closeConn: true

mybatis:
  configuration:
    call-setters-on-nulls: true

fdfs:
  soTimeout: 3000
  connectTimeout: 2000
  pool:
    maxWaitMillis: 1000
    maxTotal: 100
  charset: UTF-8
  trackerList[0]: 10.168.1.18:22122


com:
  github:
    tobato:
      fastdfs:
        tracker_http_port: 8199
        tracker_http_ip: 183.252.17.20
        protocol: http://
